spring.application.name=MedLink
server.port=${PORT:8080}

#database
spring.datasource.url=jdbc:mysql://localhost:3333/medlink
spring.datasource.username=root
spring.datasource.password=DangerArmy@3333
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-update=true